language: python
python:
  - '2.7'
  - '3.3'
install:
  - pip install coverage coveralls
script:
  - coverage run --source=rembed setup.py test
  - coveralls
  - coverage report --fail-under=100
deploy:
  provider: pypi
  user:
    secure: mGkSM8L2OsktaK7D3o2oLP3pJirV5VX+zpfZK11lWvOMQDW4q/LWOGmxNE8yTb4nkjrvVd+dHi4qqQ9805fqHl+0du7v/w/dsh9ncfQ/daWjEYaMyYOoOe2WysjDAh5BMqXgUNUTNPvLk9rGZd5r4cMlBKNB3OxNdgKayrNbxMI=
  password:
    secure: KGvWTlI/jG9wr6uUxQHVNzgMBN/da65pjX0UZ7glh+vFSjEXLE+PwfW14Zw7DAJtVuhimAmKwLQ1alHpYmXVJoPAqUoRUdWOtHLDy66AuV0nbVsDfObgORLH2d+LRTpCSYQ5FBwQBF0sDLB6a9OwBv9r347Ea0yUUSPoP5YWa6c=
  on:
    python: '2.7'
    tags: true
    repo: matt-thomson/rembed
