language: python
python:
  - '2.7'
  - '3.3'
install:
  - pip install coverage coveralls
script:
  - coverage run --source=rembed setup.py test
  - coveralls
  - coverage report --fail-under=100
deploy:
  provider: pypi
  user:
    secure: cIMONmkxJrI0C5iVSqrar2UJjopGL8eJDtAB8YisvYvE5BMLLcwBWjnFQFEGdroT/oyrD21PtgSgw8Si16x24UCayz/Lnpy2t7dca74QIphXieh5sNwfxhgZi8aeU2T6fLMLvO+eBltaCbVtzoxkw5WLAZ4+RqCiBv8H2fwWCVM=
  password:
    secure: km4ODyd6hJ3w3E+yZeb9/iLMjloxryH4n8IGaG9Fg+4VWqYbADKZlul2bmtK4UuF2ZI7xJVgom6NcoioHvVaX/GVvmMIdpYosRwXvkgpBG1sxJteiLGnKWbAECn7J3HPXgGZpXf9YpabgQNgTUwgvK8hrjRQZBSAIKmVLUvRFHw=
  on:
    python: 2.7
    tags: true
    repo: rembed/rembed
