- endpoint: http://www.ifttt.com/oembed/
  schemes:
    - http://ifttt.com/recipes/*
  example: http://ifttt.com/recipes/107745-make-a-list-of-new-books-for-your-kindle

- endpoint: http://www.youtube.com/oembed/
  schemes:
    - http://www.youtube.com/watch
  example: http://www.youtube.com/watch?v=-UUx10KOWIE

- endpoint: http://www.flickr.com/services/oembed/
  schemes:
    - http://*.flickr.com/photos/*
    - http://flic.kr/p/*
  example: http://flickr.com/photos/bees/2362225867/

- endpoint: http://www.viddler.com/oembed/
  schemes:
    - http://www.viddler.com/v/*
  example: http://www.viddler.com/v/1646c55

- endpoint: http://revision3.com/api/oembed/
  schemes: 
    - http://revision3.com/*
  example: http://revision3.com/diggnation/2008-04-17xsanned/

- endpoint: http://www.hulu.com/api/oembed.{format}
  schemes:
    - http://www.hulu.com/watch/*
  example: http://www.hulu.com/watch/20807/late-night-with-conan-obrien-wed-may-21-2008

- endpoint: http://vimeo.com/api/oembed.{format}
  schemes:
    - http://vimeo.com/*
    - http://vimeo.com/groups/*/videos/*
  example: http://vimeo.com/7100569

- endpoint: http://www.collegehumor.com/oembed.{format}
  schemes:
    - http://www.collegehumor.com/video/*
  example: http://www.collegehumor.com/video/3922232/prank-war-7-the-half-million-dollar-shot

- endpoint: http://www.jest.com/oembed.{format}
  schemes: 
    - http://www.jest.com/video/*
    - http://www.jest.com/embed/*
  example: http://www.jest.com/video/197394/paul-ryan-rap

- endpoint: http://www.polleverywhere.com/services/oembed/
  schemes:
    - http://www.polleverywhere.com/polls/*
    - http://www.polleverywhere.com/multiple_choice_polls/*
    - http://www.polleverywhere.com/free_text_polls/*
  example: http://www.polleverywhere.com/multiple_choice_polls/LTIwNzM1NTczNTE

- endpoint: http://www.ifixit.com/Embed
  schemes:
    - http://www.ifixit.com/Guide/View/*
  example: http://www.ifixit.com/Guide/View/iPhone+1st+Generation+Display+Assembly+Replacement/449

- endpoint: http://api.smugmug.com/services/oembed/
  schemes:
    - http://*.smugmug.com/*
  example: http://www.smugmug.com/popular/all#125787395_hQSj9

- endpoint: http://backend.deviantart.com/oembed
  schemes:
    - http://*.deviantart.com/art/*
    - http://*.deviantart.com/*#/d*
    - http://fav.me/*
    - http://sta.sh/*
  example: http://browse.deviantart.com/art/Vita-Brevis-379998342

- endpoint: http://www.slideshare.net/api/oembed/2
  schemes:
    - http://www.slideshare.net/*/*
  example: http://www.slideshare.net/haraldf/business-quotes-for-2011

- endpoint: http://chirb.it/oembed.{format}
  schemes:
    - http://chirb.it/*
  format: xml
  example: http://chirb.it/OBnAr1

- endpoint: http://www.nfb.ca/remote/services/oembed/
  schemes:
    - http://*.nfb.ca/film/*
  example: http://www.nfb.ca/film/aboriginality

- endpoint: http://www.scribd.com/services/oembed/
  schemes:
    - http://www.scribd.com/doc/*
  example: http://www.scribd.com/doc/110799637/Synthesis-of-Knowledge-Effects-of-Fire-and-Thinning-Treatments-on-Understory-Vegetation-in-Dry-U-S-Forests

- endpoint: http://dotsub.com/services/oembed
  schemes: 
    - http://dotsub.com/view/*
  example: http://dotsub.com/view/665bd0d5-a9f4-4a07-9d9e-b31ba926ca78

- endpoint: http://animoto.com/oembeds/create
  schemes:
    - http://animoto.com/play/*
  format: xml
  example: http://animoto.com/play/JzwsBn5FRVxS0qoqcBP5zA

- endpoint: http://www.rdio.com/api/oembed/
  schemes:
    - http://*.rdio.com/artist/*
    - http://*.rdio.com/people/*
  example: http://www.rdio.com/artist/The_Black_Keys/album/Brothers/

- endpoint: http://www.mixcloud.com/oembed/
  schemes:
    - http://www.mixcloud.com/*/*/
  example: http://www.mixcloud.com/TechnoLiveSets/jon_rundell-live-electrobeach-festival-benidorm-16-08-2013/

- endpoint: http://api.clyp.it/oembed/
  schemes:
    - http://clyp.it/*
    - http://clyp.it/playlist/*
  example: http://clyp.it/zhwuptos

- endpoint: http://www.screenr.com/api/oembed.{format}
  schemes:
    - http://*.screenr.com/*
  example: http://screenr.com/3jns

- endpoint: http://www.funnyordie.com/oembed.{format}
  schemes:
    - http://www.funnyordie.com/videos/*
  example: http://www.funnyordie.com/videos/a7311134ac/patton-oswalt-in-heavy-metal

- endpoint: http://polldaddy.com/oembed/
  schemes:
    - http://*.polldaddy.com/s/*
    - http://*.polldaddy.com/poll/*
    - http://*.polldaddy.com/ratings/*
  example: http://polldaddy.com/ratings/39

- endpoint: http://www.ted.com/talks/oembed.{format}
  schemes:
    - http://*.ted.com/talks/*
  example: http://www.ted.com/talks/jill_bolte_taylor_s_powerful_stroke_of_insight.html

- endpoint: http://www.videojug.com/oembed.{format}
  schemes:
    - http://www.videojug.com/film/*
    - http://www.videojug.com/interview/*
  example: http://www.videojug.com/film/how-to-tie-a-knot-braid

- endpoint: http://videos.sapo.pt/oembed
  schemes:
    - http://videos.sapo.pt/*
  example: http://videos.sapo.pt/dNbiosGa9YZHfLrhkA88

- endpoint: http://api.justin.tv/api/embed/from_url.{format}
  schemes:
    - http://www.justin.tv/*
  example: http://www.justin.tv/deepellumonair

- endpoint: http://official.fm/services/oembed.{format}
  schemes:
    - http://official.fm/tracks/*
    - http://official.fm/playlists/*
  example: http://official.fm/tracks/npTR

- endpoint: http://huffduffer.com/oembed
  schemes:
    - http://huffduffer.com/*/*
  example: http://huffduffer.com/jxpx777/125342

- endpoint: http://shoudio.com/api/oembed
  schemes:
    - http://shoudio.com/*
    - http://shoud.io/*
  format: json
  example: http://shoudio.com/user/shoister/status/8122

- endpoint: http://api.mobypicture.com/oEmbed
  schemes:
    - http://*.mobypicture.com/user/*/view/*
    - http://moby.to/*
  example: http://mobypicture.com/user/Henk_Voermans/view/15880044

- endpoint: http://www.23hq.com/23/oembed
  schemes:
    - http://www.23hq.com/*/photo/*
  example: http://www.23hq.com/mprove/photo/13297717

